# Generated by Django 3.2.3 on 2021-06-30 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObra',
            fields=[
                ('id_categoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Categoria obra')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('idObra', models.IntegerField(primary_key=True, serialize=False, verbose_name='id solicitud obra')),
                ('nombreObra', models.CharField(max_length=40, verbose_name='nombre obra')),
                ('historia', models.TextField(max_length=3000, verbose_name='historia obra')),
                ('descripcion', models.TextField(max_length=1000, verbose_name='descripcion obra')),
                ('precio', models.CharField(max_length=100, verbose_name='precio obra')),
                ('tecnicaUsada', models.TextField(max_length=1000, verbose_name='tecnica usada obra')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.categoriaobra')),
            ],
        ),
    ]
